# Generated by Django 4.2.11 on 2024-12-09 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model_ToDoWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("detail", models.TextField(max_length=300)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
